# ============================================
#       KitsAdvanced - Configuration
# ============================================
# Language / Idioma: 'en' or 'es'
idioma: en

# Sistema de Mensajes Personalizables
mensajes:
  es:
    prefix: "&8[&bKitsAdvanced&8] &7» "
    kit-received: "&b&lKITS &8| &eHas recibido el kit &f%kit%&e. ¡Disfrútalo!"
    no-permission: "&4&l¡VAYA! &cNo tienes los permisos necesarios para esto."
    reload: "&a&lRECARGA: &7La configuración ha sido actualizada sin lag."
    kit-created: "&a&l¡ÉXITO! &eEl kit &b%kit% &eha sido creado correctamente."
    wait: "&c&lESPERA: &7Faltan &e%time% &7para volver a usarlo."
  
  en:
    prefix: "&8[&bKitsAdvanced&8] &7» "
    kit-received: "&b&lKITS &8| &eYou received the &f%kit% &ekit. Enjoy!"
    no-permission: "&4&lWHOOPS! &cYou don't have permission for this."
    reload: "&a&lRELOAD: &7Configuration updated with zero lag."
    kit-created: "&a&lSUCCESS! &eThe kit &b%kit% &ehas been created."
    wait: "&c&lWAIT: &7You need to wait &e%time% &7more."

# Datos internos (Manejados por el plugin)
kits:
  # Kit de ejemplo para que el archivo no esté vacío
  ejemplo:
    requiere-permiso: false
    tiempo: 60
    items: []

usuarios: {}
