name: AdvancedKits
version: 1.0
main: me.adrian.kits.Principal
api-version: 1.20 # O la versión que estés usando
commands:
  akits:
    description: Comando principal de kits
    aliases: [kits, kit]
permissions:
  kitsadvanced.admin:
    description: Permite usar el panel de administrador
    default: op
